import numpy as np
import json
import os
from datetime import datetime as dt

from src.helpers import PATH_DATA

# This Module's sole purpose is to generate Decks and save them to disk

PATH_TO_LOAD = os.path.join('data','to_load')
HALF_DECK_SIZE = 26

def get_decks(n_decks: int,
              seed: int,
              half_deck_size: int = HALF_DECK_SIZE
             ) -> tuple[np.ndarray, np.ndarray]:
    """
    Efficiently generate `n_decks` shuffled decks using NumPy.
    
    Returns:
        decks (np.ndarray): 2D array of shape (n_decks, num_cards), 
        each row is a shuffled deck.

    """
    init_deck = [0]*half_deck_size + [1]*half_deck_size  # Base deck
    decks = np.tile(init_deck, (n_decks, 1))
    rng = np.random.default_rng(seed)
    rng.permuted(decks, axis=1, out=decks)
    
    return decks


#for creates a timestamp
def timestamp() -> str:
    """
    creates a timestamp
    """
    t = str(dt.now())
    r = t.replace(' ', '-').replace(':', '-').replace('.', '-')
    return r


#stores data generated by get_decks()
def store_decks(n_decks: int,
                seed: int, 
                result_decks: np.ndarray,
                path_data: str = PATH_DATA
               )-> dict:
    
    """
    Stores the data generated by get_decks() function into
        .npy file and .json file
    seed and num_decks stored separately from random decks
    """

    # creates a directory
    os.makedirs(PATH_TO_LOAD, exist_ok=True)

    # save self from overwriting with a timestamp
    ts = timestamp()

    # name of the file that will be saved
    npy_file = f"seed{seed}_decks{n_decks}_timestamp{ts}.npy"
    npy_path = os.path.join(PATH_TO_LOAD, npy_file)

    json_path = os.path.join(path_data, 'settings.json')
    
    # if it exists, then load the file
    # if not, then create new one
    if os.path.exists(json_path):
        with open(json_path,'r') as f:
            settings = json.load(f)
    else:
        settings = {}
            
    if npy_file in settings:
        return settings

    #save the decks into the npy file
    #random decks stored in the .npy file
    np.save(npy_path, result_decks)

    # information gets saved into a .npy file
    settings[npy_file] = {}
    settings[npy_file]['seed'] = seed
    settings[npy_file]['n'] = n_decks


    with open(json_path, 'w') as f:
        json.dump(settings, f)
    
    return settings